# Generated by Django 6.0 on 2026-01-08 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Inquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "service",
                    models.CharField(
                        choices=[
                            ("REAL_ESTATE", "Real Estate Inquiry"),
                            ("CONSTRUCTION", "Construction Project"),
                            ("CONSULTANCY", "Consultancy Services"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("date_sent", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
