# Generated by Django 6.0 on 2026-01-08 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=200)),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[("SALE", "For Sale"), ("RENT", "For Rent")],
                        default="SALE",
                        max_length=10,
                    ),
                ),
                ("image", models.ImageField(upload_to="properties/")),
                ("is_published", models.BooleanField(default=True)),
                ("list_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Product",
        ),
    ]
