# Generated by Django 6.0 on 2026-01-08 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_property_delete_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="bathrooms",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="property",
            name="bedrooms",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="property",
            name="sqft",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="PropertyImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="properties/gallery/")),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="products.property",
                    ),
                ),
            ],
        ),
    ]
