# Generated by Django 6.0 on 2026-01-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0003_property_bathrooms_property_bedrooms_property_sqft_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
    ]
